import { StyleSheet, Dimensions } from 'react-native';


export default StyleSheet.create({
    HomePage: {
      position: "relative",
      display: "flex",
      flexDirection: "column",
      justifyContent: "flex-start",
      alignItems: "flex-start",
      width: 390,
      height: 844,
      paddingTop: 28,
      borderRadius: 63,
      boxSizing: "border-box",
      backgroundColor: "rgba(0,0,0,1)",
      transform: "rotate(-180deg);",
    },
    _52Gaj: {
      position: "absolute",
      top: 449,
      left: 330,
      display: "flex",
      flexDirection: "row",
      alignItems: "flex-end",
      width: 136,
      height: 148,
      paddingBottom: 27,
      boxSizing: "border-box",
    },
    Rectangle17: {
      width: "100%",
      height: 116,
    },
    _52KaDamanRenukaPawa: {
      color: "rgba(223,239,240,0.8)",
      fontSize: "12px",
      lineHeight: "12px",
      fontFamily: "Inter, sans-serif",
      fontWeight: "400",
    },
    Group689: {
      position: "absolute",
      top: 28,
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      width: "100%",
      height: "100%",
      boxSizing: "border-box",
    },
    Group1038: {
      display: "flex",
      flexDirection: "column",
      width: "100%",
      boxSizing: "border-box",
    },
    Group578: {
      display: "flex",
      flexDirection: "row",
      alignItems: "flex-end",
      width: "100%",
      boxSizing: "border-box",
    },
    HiHugo: {
      color: "rgba(223,239,240,1)",
      fontSize: "24px",
      lineHeight: "24px",
      fontFamily: "Inter, sans-serif",
      fontWeight: "400",
    },
    Lines: {
      width: 24,
      height: 16.94,
    },
    ExploraTuMusicaFavor: {
      color: "rgba(223,239,240,0.8)",
      fontSize: "10px",
      lineHeight: "10px",
      fontFamily: "Inter, sans-serif",
      fontWeight: "400",
    },
    SearchBar: {
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      width: "100%",
      paddingLeft: 12,
      paddingRight: 10,
      paddingTop: 14,
      paddingBottom: 13,
      borderRadius: 10,
      boxSizing: "border-box",
      backgroundColor: "rgba(35,39,40,1)",
    },
    AntDesignSearchOutlined: {
      width: 20.18,
      height: 20,
    },
    ArtistaAlbMMSica: {
      color: "rgba(236,236,236,1)",
      fontSize: "16px",
      lineHeight: "16px",
      fontFamily: "Inter, sans-serif",
      fontWeight: "400",
    },
    Mic: {
      width: 24.21,
      height: "100%",
    },
    Artistas: {
      color: "rgba(255,255,255,1)",
      fontSize: "20px",
      lineHeight: "20px",
      fontFamily: "Inter, sans-serif",
      fontWeight: "400",
    },
    Group926: {
      display: "flex",
      flexDirection: "row",
      width: "100%",
      boxSizing: "border-box",
    },
    ArjitSing: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      height: "100%",
      paddingBottom: 3,
      boxSizing: "border-box",
    },
    Ellipse1: {
      width: "100%",
      height: 101,
    },
    ArjitSingh: {
      color: "rgba(223,239,240,0.8)",
      fontSize: "12px",
      lineHeight: "12px",
      fontFamily: "Inter, sans-serif",
      fontWeight: "400",
    },
    Justin: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      height: "100%",
      paddingBottom: 3,
      boxSizing: "border-box",
    },
    Ellipse2: {
      width: "100%",
      height: 101,
    },
    JustinBieber: {
      color: "rgba(223,239,240,0.8)",
      fontSize: "12px",
      lineHeight: "12px",
      fontFamily: "Inter, sans-serif",
      fontWeight: "400",
    },
    HoneySingh1: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      height: "100%",
      paddingBottom: 3,
      boxSizing: "border-box",
    },
    Ellipse3: {
      width: "100%",
      height: 101,
    },
    HoneySingh: {
      color: "rgba(223,239,240,0.8)",
      fontSize: "12px",
      lineHeight: "12px",
      fontFamily: "Inter, sans-serif",
      fontWeight: "400",
    },
    BottomBar: {
      width: "100%",
      height: 52,
    },
    Group735: {
      position: "absolute",
      top: 155,
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      width: 347,
      height: 443,
      boxSizing: "border-box",
    },
    Group841: {
      position: "relative",
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-end",
      width: "100%",
      boxSizing: "border-box",
    },
    Group396: {
      display: "flex",
      flexDirection: "row",
      alignItems: "flex-end",
      width: "100%",
      boxSizing: "border-box",
    },
    Line4: {
      width: "100%",
      height: 1,
      borderWidth: 1,
      borderColor: "rgba(194,250,241,0.2)",
      transform: "rotate(-180deg);",
    },
    CardComponent: {
      width: 192,
      height: "100%",
    },
    VeiwAll: {
      position: "relative",
      width: 61,
      height: 15,
      boxSizing: "border-box",
    },
    VerTodo: {
      position: "absolute",
      color: "rgba(255,255,255,1)",
      fontSize: "12px",
      lineHeight: "12px",
      fontFamily: "Inter, sans-serif",
      fontWeight: "400",
    },
    EpArrowRight: {
      position: "absolute",
      left: 46,
      width: 15,
      height: "100%",
    },
    EscChaloAhora: {
      position: "absolute",
      top: 97,
      left: -20,
      color: "rgba(255,255,255,1)",
      fontSize: "20px",
      lineHeight: "20px",
      fontFamily: "Inter, sans-serif",
      fontWeight: "400",
    },
    Group991: {
      display: "flex",
      flexDirection: "row",
      width: "100%",
      boxSizing: "border-box",
    },
    Filhal: {
      display: "flex",
      flexDirection: "row",
      alignItems: "flex-end",
      height: "100%",
      paddingBottom: 27,
      boxSizing: "border-box",
    },
    Rectangle15: {
      width: "100%",
      height: 116,
    },
    FilhallBParkFilhall: {
      color: "rgba(223,239,240,0.8)",
      fontSize: "12px",
      lineHeight: "12px",
      fontFamily: "Inter, sans-serif",
      fontWeight: "400",
    },
    Ranjha: {
      display: "flex",
      flexDirection: "row",
      alignItems: "flex-end",
      height: "100%",
      paddingBottom: 27,
      boxSizing: "border-box",
    },
    Rectangle16: {
      width: "100%",
      height: 116,
    },
    RanjhaBParkRanhja: {
      color: "rgba(223,239,240,0.8)",
      fontSize: "12px",
      lineHeight: "12px",
      fontFamily: "Inter, sans-serif",
      fontWeight: "400",
    },
    Frame13761: {
      position: "absolute",
      top: 355,
      left: -36.77,
      display: "flex",
      flexDirection: "row",
      justifyContent: "flex-start",
      alignItems: "flex-start",
      width: 344.71,
      height: 27.97,
      boxSizing: "border-box",
      transform: "rotate(-180deg);",
    },
    AvisMeSiempre: {
      marginRight: 39.77143096923828,
      backgroundColor: " linear-gradient(113.38deg, rgba(254,254,254,1) 0%) ",
      fontSize: "11.88px",
      lineHeight: "11.88px",
      fontFamily: "Inter, sans-serif",
      fontWeight: "500",
    },
    Frame13759: {
      display: "flex",
      flexDirection: "column",
      justifyContent: "flex-start",
      alignItems: "flex-start",
      height: "100%",
      marginRight: 39.77143096923828,
      paddingLeft: 5.49,
      paddingRight: 5.49,
      paddingTop: 4.11,
      paddingBottom: 4.11,
      borderRadius: 31.54,
      boxSizing: "border-box",
      backgroundColor:
        " linear-gradient(180deg, rgba(42,66,89,1) 0%, rgba(8,16,23,0) 100%) ",
    },
    Frame13758: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      width: "100%",
      height: "100%",
      boxSizing: "border-box",
    },
    IniciaAqu: {
      marginRight: 2.7428572177886963,
      backgroundColor:
        " linear-gradient(100.27000000000001deg, rgba(254,254,254,1) 0%) ",
      fontSize: "14.26px",
      lineHeight: "14.26px",
      fontFamily: "Inter, sans-serif",
      fontWeight: "600",
    },
    Play: {
      width: 13.71,
      height: 13.71,
      marginRight: 2.7428572177886963,
    },
  })